### ISSUE TITLE
fichiers eligible_pour_bourse manquant

### ISSUE THREAD

**Issue by noelma** [Florian-Merle/el-demo#1]
Bonjour,

Merci pour votre talk de l'afup day lyon 2023 qui fût enrichissant personnellement et professionnellement :heart:

J'ai essayé d'installer votre démo mais, le fichier `var/eligible_pour_bourse` est manquant.

Pourriez-vous l'ajouter ? Merci :pray:

**Comment by Elkawaie** [comment]
Salut @noelma,

Sur ce sujet, il est possible de juste créer un simple fichier texte dans le `var`, je te rejoins sur le fait qu'un Readme (cf: #2 ) serait appréciable.

Encore merci pour votre talk :pray:

**Comment by Florian-Merle** [comment]
Bonjour, je viens de pousser le correctif pour éviter d'avoir l'erreur. Merci pour les retours sur le talk !
